### ISSUE TITLE
Ref genome install error

### ISSUE THREAD

**Issue by gevro** [AlexandrovLab/SigProfilerMatrixGeneratorR#18]
Hi,
I'm getting the below error. Is this a known issue?
Thanks!

```
> install('GRCh37', rsync=FALSE, bash=TRUE)
Error in py_module_import(module, convert = convert) : 
  ImportError: dlopen(/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_main'
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/SigProfilerMatrixGenerator/install.py", line 14, in <module>
    from scipy import spatial
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._spherical_voronoi import SphericalVoronoi
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/spatial/_spherical_voronoi.py", line 18, in <module>
    from scipy.spatial.distance import pdist
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/spatial/distance.py", line 124, in <module>
    from ..linalg import norm
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ImportError: dlopen(/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_main'

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─reticulate::import("SigProfilerMatrixGenerator.install")
 3.     └─reticulate:::py_module_import(module, convert = convert)
 ```

**Comment by gevro** [comment]
Ah, I think the issue is that I need to install the genome manually in python first:
genInstall.install('GRCh37', rsync=False, bash=True)

This is in the SigProfilerMatrixGenerator installation instructions but not in the SigProfilerMatrixGeneratorR instructions.

**Comment by gevro** [comment]
Actually, that is not the issue. It seems that the issue is there is no 'install' function in they SigProfilerMatrixGenerator Python package, which reticulate tries to load:

```
> reticulate::import("SigProfilerMatrixGenerator.install")
Error in py_module_import(module, convert = convert) : 
  ImportError: dlopen(/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_main'
Run `reticulate::py_last_error()` for details.
```

Seems like there might be an inconsistency between SigProfilerMatrixGeneratorR and SigProfilerMatrixGenerator.

**Comment by marcos-diazg** [comment]
Hi @gevro,

Thanks for your question. Have you installed the Python package SigProfilerMatrixGenerator before starting using SigProfilerMatrixGeneratorR? Both need to be installed for you to be able to use the functions of SigProfilerMatrixGeneratorR in R. Also, please use the `py_config()` function to ensure you are using the Python version where you have previously installed SigProfilerMatrixGenerator.

I hope this helps. Best,

Marcos

**Comment by gevro** [comment]
Yes I installed the python package first, and it loads fine via reticulate:

```
> reticulate::import("SigProfilerMatrixGenerator")
Module(SigProfilerMatrixGenerator)
```

And py_config() matches the python version into which the package was installed:
```
py_config()
python:         /Applications/anaconda3/bin/python
libpython:      /Applications/anaconda3/lib/libpython3.7m.dylib
pythonhome:     /Applications/anaconda3:/Applications/anaconda3
version:        3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Applications/anaconda3/lib/python3.7/site-packages/numpy
numpy_version:  1.21.6

NOTE: Python version was forced by use_python() function
```

**Comment by marcos-diazg** [comment]
Can you please let me know which version of both SigProfilerMatrixGenerator and SigProfilerMatrixGeneratorR are you using? Also, if you could send the actual commands you are running, I can try reproducing your issue on my end. Thanks.

**Comment by gevro** [comment]
Sure.
1. Installed python package: pip install SigProfilerMatrixGenerator
- SigProfilerMatrixGenerator-1.2.13
2. Installed R package (installed today so it must be the latest version)
install_github("AlexandrovLab/SigProfilerMatrixGeneratorR")
3. library("SigProfilerMatrixGeneratorR")
4. install('GRCh37', rsync=FALSE, bash=TRUE)
-> This command gives the error:
Error in py_module_import(module, convert = convert) : 
  ImportError: dlopen(/Applications/anaconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_main'
Run `reticulate::py_last_error()` for details.

Python version is listed above.

**Comment by gevro** [comment]
And no worries if you can't find the issue - I can transition to using the python package directly.

**Comment by marcos-diazg** [comment]
Sorry, but I was not able to reproduce your issue. Maybe the code below (similar to the one in the README) can be helpful. Also, thanks for your understanding and for directly proposing transitioning to the Python package.

Please let us know if we can help with anything else, and thanks for your interest!

```
conda create --name spmg_r -y
conda activate spmg_r
conda install python=3.10 r-base r-devtools r-reticulate -c conda-forge -y
pip install SigProfilerMatrixGenerator
R
library(devtools)
install_github("AlexandrovLab/SigProfilerMatrixGeneratorR")
library(reticulate)
use_python('/Users/mdiazgay/opt/miniconda3/envs/spmg_r/bin/python3.10') #Please change it for your own path
library("SigProfilerMatrixGeneratorR")
install('GRCh37', rsync=FALSE, bash=TRUE)
```
